#!/usr/bin/env sh
#
# Copyright (c) 2016 Michael Tuexen
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

packetdrill=/usr/local/bin/packetdrill
delay=1
timelimit=100
testcases="snd-syn/snd-syn-with-default-options-ipv4 \
           snd-syn/snd-syn-with-default-options-ipv6 \
           snd-syn/snd-syn-without-options-ipv4 \
           snd-syn/snd-syn-without-options-ipv6 \
           snd-syn/snd-syn-rtx-keepinit-ipv4 \
           snd-syn/snd-syn-rtx-keepinit-ipv6 \
           snd-syn/snd-syn-rtx-max-number-ipv4 \
           snd-syn/snd-syn-rtx-max-number-ipv6 \
           snd-syn/snd-syn-rtx-drop-options-ipv4 \
           snd-syn/snd-syn-rtx-drop-options-ipv6 \
           snd-syn/snd-syn-mss-inherited-from-mtu-72-ipv4 \
           snd-syn/snd-syn-mss-inherited-from-mtu-9000-ipv4 \
           snd-syn/snd-syn-mss-inherited-from-mtu-65535-ipv4 \
           snd-syn/snd-syn-mss-inherited-from-mtu-1280-ipv6 \
           snd-syn/snd-syn-mss-inherited-from-mtu-9000-ipv6 \
           snd-syn/snd-syn-mss-inherited-from-mtu-65535-ipv6 \
           snd-syn/snd-syn-without-sack-ipv4 \
           snd-syn/snd-syn-without-sack-ipv6 \
           snd-syn/snd-syn-without-ws-and-ts-ipv4 \
           snd-syn/snd-syn-without-ws-and-ts-ipv6 \
           snd-syn/snd-syn-without-sack-and-ws-and-ts-ipv4 \
           snd-syn/snd-syn-without-sack-and-ws-and-ts-ipv6 \
           snd-syn/snd-syn-with-min-ws-ipv4 \
           snd-syn/snd-syn-with-min-ws-ipv6 \
           snd-syn/snd-syn-with-max-ws-ipv4 \
           snd-syn/snd-syn-with-max-ws-ipv6 \
           snd-syn/snd-syn-with-ecn-ipv4 \
           snd-syn/snd-syn-with-ecn-ipv6 \
           snd-syn/snd-syn-with-ecn-alt-maxretries-ipv4 \
           snd-syn/snd-syn-with-ecn-alt-maxretries-ipv6 \
           rcv-icmp/rcv-icmp-hard-error-proto-unreachable-ipv4 \
           rcv-icmp/rcv-icmp-hard-error-proto-unreachable-ipv6 \
           rcv-icmp/rcv-icmp-hard-error-port-unreachable-ipv4 \
           rcv-icmp/rcv-icmp-hard-error-port-unreachable-ipv6 \
           rcv-icmp/rcv-icmp-hard-error-net-prohibited-ipv4 \
           rcv-icmp/rcv-icmp-hard-error-host-prohibited-ipv4 \
           rcv-icmp/rcv-icmp-hard-error-comm-prohibited-ipv4 \
           rcv-icmp/rcv-icmp-hard-error-comm-prohibited-ipv6 \
           rcv-icmp/rcv-icmp-hard-error-ttl-exceeded-ipv4 \
           rcv-icmp/rcv-icmp-hard-error-ttl-exceeded-ipv6 \
           rcv-icmp/rcv-icmp-hard-error-ignored-ipv4 \
           rcv-icmp/rcv-icmp-hard-error-ignored-ipv6 \
           state-event-engine/rcv-rst-closed/rcv-rst-closed-secure-ipv4 \
           state-event-engine/rcv-rst-closed/rcv-rst-closed-secure-ipv6 \
           state-event-engine/rcv-rst-listen/rcv-rst-listen-secure-ipv4 \
           state-event-engine/rcv-rst-listen/rcv-rst-listen-secure-ipv6 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-outside-left-secure-ipv4 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-outside-left-secure-ipv6 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-left-edge-secure-ipv4 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-left-edge-secure-ipv6 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-right-edge-secure-ipv4 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-right-edge-secure-ipv6 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-outside-right-secure-ipv4 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-outside-right-secure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-outside-left-secure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-outside-left-secure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-left-edge-secure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-left-edge-secure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-right-edge-secure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-right-edge-secure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-outside-right-secure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-outside-right-secure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-outside-left-secure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-outside-left-secure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-left-edge-secure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-left-edge-secure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-right-edge-secure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-right-edge-secure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-outside-right-secure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-outside-right-secure-ipv6 \
           state-event-engine/rcv-rst-established/rcv-rst-established-outside-left-secure-ipv4 \
           state-event-engine/rcv-rst-established/rcv-rst-established-outside-left-secure-ipv6 \
           state-event-engine/rcv-rst-established/rcv-rst-established-left-edge-secure-ipv4 \
           state-event-engine/rcv-rst-established/rcv-rst-established-left-edge-secure-ipv6 \
           state-event-engine/rcv-rst-established/rcv-rst-established-right-edge-secure-ipv4 \
           state-event-engine/rcv-rst-established/rcv-rst-established-right-edge-secure-ipv6 \
           state-event-engine/rcv-rst-established/rcv-rst-established-outside-right-secure-ipv4 \
           state-event-engine/rcv-rst-established/rcv-rst-established-outside-right-secure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-left-secure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-left-secure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-left-edge-secure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-left-edge-secure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-right-edge-secure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-right-edge-secure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-right-secure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-right-secure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-left-secure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-left-secure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-left-edge-secure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-left-edge-secure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-right-edge-secure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-right-edge-secure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-right-secure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-right-secure-ipv6 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-outside-left-secure-ipv4 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-outside-left-secure-ipv6 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-left-edge-secure-ipv4 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-left-edge-secure-ipv6 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-right-edge-secure-ipv4 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-right-edge-secure-ipv6 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-outside-right-secure-ipv4 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-outside-right-secure-ipv6 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-outside-left-secure-ipv4 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-outside-left-secure-ipv6 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-left-edge-secure-ipv4 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-left-edge-secure-ipv6 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-right-edge-secure-ipv4 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-right-edge-secure-ipv6 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-outside-right-secure-ipv4 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-outside-right-secure-ipv6 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-outside-left-secure-ipv4 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-outside-left-secure-ipv6 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-left-edge-secure-ipv4 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-left-edge-secure-ipv6 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-right-edge-secure-ipv4 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-right-edge-secure-ipv6 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-outside-right-secure-ipv4 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-outside-right-secure-ipv6 \
           state-event-engine/rcv-rst-closed/rcv-rst-closed-insecure-ipv4 \
           state-event-engine/rcv-rst-closed/rcv-rst-closed-insecure-ipv6 \
           state-event-engine/rcv-rst-listen/rcv-rst-listen-insecure-ipv4 \
           state-event-engine/rcv-rst-listen/rcv-rst-listen-insecure-ipv6 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-outside-left-insecure-ipv4 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-outside-left-insecure-ipv6 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-left-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-left-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-right-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-right-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-outside-right-insecure-ipv4 \
           state-event-engine/rcv-rst-syn-sent/rcv-rst-syn-sent-outside-right-insecure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-outside-left-insecure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-outside-left-insecure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-left-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-left-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-right-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-right-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-outside-right-insecure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-listen-outside-right-insecure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-outside-left-insecure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-outside-left-insecure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-left-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-left-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-right-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-right-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-outside-right-insecure-ipv4 \
           state-event-engine/rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-via-syn-sent-outside-right-insecure-ipv6 \
           state-event-engine/rcv-rst-established/rcv-rst-established-outside-left-insecure-ipv4 \
           state-event-engine/rcv-rst-established/rcv-rst-established-outside-left-insecure-ipv6 \
           state-event-engine/rcv-rst-established/rcv-rst-established-left-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-established/rcv-rst-established-left-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-established/rcv-rst-established-right-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-established/rcv-rst-established-right-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-established/rcv-rst-established-outside-right-insecure-ipv4 \
           state-event-engine/rcv-rst-established/rcv-rst-established-outside-right-insecure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-left-insecure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-left-insecure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-left-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-left-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-right-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-right-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-right-insecure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-right-insecure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-left-insecure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-left-insecure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-left-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-left-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-right-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-right-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-right-insecure-ipv4 \
           state-event-engine/rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-right-insecure-ipv6 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-outside-left-insecure-ipv4 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-outside-left-insecure-ipv6 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-left-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-left-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-right-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-right-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-outside-right-insecure-ipv4 \
           state-event-engine/rcv-rst-close-wait/rcv-rst-close-wait-outside-right-insecure-ipv6 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-outside-left-insecure-ipv4 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-outside-left-insecure-ipv6 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-left-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-left-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-right-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-right-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-outside-right-insecure-ipv4 \
           state-event-engine/rcv-rst-closing/rcv-rst-closing-outside-right-insecure-ipv6 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-outside-left-insecure-ipv4 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-outside-left-insecure-ipv6 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-left-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-left-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-right-edge-insecure-ipv4 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-right-edge-insecure-ipv6 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-outside-right-insecure-ipv4 \
           state-event-engine/rcv-rst-last-ack/rcv-rst-last-ack-outside-right-insecure-ipv6 \
           socket-api/getsockopt/socket-api-getsockopt-keepcnt-inherited-from-sysctl-ipv4 \
           socket-api/getsockopt/socket-api-getsockopt-keepcnt-inherited-from-sysctl-ipv6 \
           socket-api/getsockopt/socket-api-getsockopt-keepidle-inherited-from-sysctl-ipv4 \
           socket-api/getsockopt/socket-api-getsockopt-keepidle-inherited-from-sysctl-ipv6 \
           socket-api/getsockopt/socket-api-getsockopt-keepinit-inherited-from-sysctl-ipv4 \
           socket-api/getsockopt/socket-api-getsockopt-keepinit-inherited-from-sysctl-ipv6 \
           socket-api/getsockopt/socket-api-getsockopt-keepintvl-inherited-from-sysctl-ipv4 \
           socket-api/getsockopt/socket-api-getsockopt-keepintvl-inherited-from-sysctl-ipv6"

rootdir=`/usr/bin/dirname $0`
passed=0
failed=0
run=0
skipped=0
timedout=0
killed=0
first=1

printf "Name                                                                    Verdict\n"
printf "===============================================================================\n"
for testcase in $testcases
do
  printf "%-68.68s " `/usr/bin/basename $testcase`
  if [ $first -eq 0 ] ; then
    if [ $delay -ne 0 ] ; then
      if [ -t 1 ] ; then
        printf "\033[33m%10s\033[0m" "WAITING"
      fi
      sleep $delay
      if [ -t 1 ] ; then
        printf "\b\b\b\b\b\b\b\b\b\b"
      fi
    fi
  else
    first=0
  fi
  if [ -t 1 ] ; then
    printf "\033[33m%10s\033[0m" "RUNNING"
  fi
  if [ -f ${rootdir}/${testcase}.pkt ] ; then
    timeout $timelimit $packetdrill ${rootdir}/${testcase}.pkt >/dev/null 2>${rootdir}/${testcase}.out
    result=$?
    found=1
  else
    found=0
  fi
  if [ -t 1 ] ; then
    printf "\b\b\b\b\b\b\b\b\b\b"
  fi
  if [ $found -eq 1 ] ; then
    case $result in
      0)
         passed=`expr $passed + 1`
         if [ -t 1 ] ; then
           printf "\033[32m%10s\033[0m\n" "PASSED"
         else
           printf "%10s\n" "PASSED"
         fi
         ;;
      1)
         failed=`expr $failed + 1`
         if [ -t 1 ] ; then
           printf "\033[31m%10s\033[0m\n" "FAILED"
         else
           printf "%10s\n" "FAILED"
         fi
         ;;
      124)
         timedout=`expr $timedout + 1`
         if [ -t 1 ] ; then
           printf "\033[35m%10s\033[0m\n" "TIMEDOUT"
         else
           printf "%10s\n" "TIMEDOUT"
         fi
         ;;
      129|1[345]?|16[01])
         killed=`expr $killed + 1`
         if [ -t 1 ] ; then
           printf "\033[30m%10s\033[0m\n" "KILLED(`expr $result - 128`)"
         else
           printf "%10s\n" "KILLED(`expr $result - 128`)"
         fi
         ;;
      *)
         if [ -t 1 ] ; then
           printf "\033[36m%10s\033[0m\n" "UNKNOWN"
         else
           printf "%10s\n" "UNKNOWN"
         fi
         ;;
    esac
    run=`expr $run + 1`
  else
    if [ -t 1 ] ; then
      printf "\033[34m%10s\033[0m\n" "SKIPPED"
    else
      printf "%10s\n" "SKIPPED"
    fi
    skipped=`expr $skipped + 1`
  fi
done
printf "===============================================================================\n"
printf "Summary: Number of tests run:       %3u\n" $run
printf "         Number of tests passed:    %3u\n" $passed
printf "         Number of tests failed:    %3u\n" $failed
printf "         Number of tests timed out: %3u\n" $timedout
printf "         Number of tests skipped:   %3u\n" $skipped
if [ $killed -gt 0 ] ; then
  printf "         Number of tests killed:    %3u\n" $killed
fi
