#!/usr/bin/env sh
#
# Copyright (c) 2016 Michael Tuexen
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

./run-tests.sh -t 400 $* \
               fast-open/client/all-fast-open-client-tests \
               fast-open/server/all-fast-open-server-tests \
               rcv-data-segments/all-rcv-data-segments-tests \
               rcv-icmp/all-rcv-icmp-tests \
               snd-syn/all-snd-syn-tests \
               snippets/all-snippets \
               socket-api/getsockopt/all-getsockopt-tests \
               socket-api/setsockopt/all-setsockopt-tests \
               state-event-engine/rcv-syn-closed/all-rcv-syn-closed-tests \
               state-event-engine/rcv-syn-listen/all-rcv-syn-listen-tests \
               state-event-engine/rcv-syn-syn-sent/all-rcv-syn-syn-sent-tests \
               state-event-engine/rcv-syn-established/all-rcv-syn-established-tests \
               state-event-engine/rcv-syn-close-wait/all-rcv-syn-close-wait-tests \
               state-event-engine/rcv-syn-fin-wait-1/all-rcv-syn-fin-wait-1-tests \
               state-event-engine/rcv-syn-closing/all-rcv-syn-closing-tests \
               state-event-engine/rcv-syn-last-ack/all-rcv-syn-last-ack-tests \
               state-event-engine/rcv-syn-fin-wait-2/all-rcv-syn-fin-wait-2-tests \
               state-event-engine/rcv-syn-time-wait/all-rcv-syn-time-wait-tests \
               state-event-engine/rcv-syn-ack-closed/all-rcv-syn-ack-closed-tests \
               state-event-engine/rcv-syn-ack-listen/all-rcv-syn-ack-listen-tests \
               state-event-engine/rcv-syn-ack-syn-sent/all-rcv-syn-ack-syn-sent-tests \
               state-event-engine/rcv-syn-fin-closed/all-rcv-syn-fin-closed-tests \
               state-event-engine/rcv-syn-fin-listen/all-rcv-syn-fin-listen-tests \
               state-event-engine/rcv-syn-fin-syn-sent/all-rcv-syn-fin-syn-sent-tests \
               state-event-engine/rcv-ack-closed/all-rcv-ack-closed-tests \
               state-event-engine/rcv-ack-listen/all-rcv-ack-listen-tests \
               state-event-engine/rcv-ack-syn-sent/all-rcv-ack-syn-sent-tests \
               state-event-engine/rcv-fin-closed/all-rcv-fin-closed-tests \
               state-event-engine/rcv-fin-listen/all-rcv-fin-listen-tests \
               state-event-engine/rcv-fin-syn-sent/all-rcv-fin-syn-sent-tests \
               state-event-engine/rcv-fin-ack-closed/all-rcv-fin-ack-closed-tests \
               state-event-engine/rcv-fin-ack-listen/all-rcv-fin-ack-listen-tests \
               state-event-engine/rcv-fin-ack-syn-sent/all-rcv-fin-ack-syn-sent-tests \
               state-event-engine/rcv-rst-closed/all-rcv-rst-closed-tests \
               state-event-engine/rcv-rst-listen/all-rcv-rst-listen-tests \
               state-event-engine/rcv-rst-syn-sent/all-rcv-rst-syn-sent-tests \
               state-event-engine/rcv-rst-syn-rcvd/all-rcv-rst-syn-rcvd-tests \
               state-event-engine/rcv-rst-established/all-rcv-rst-established-tests \
               state-event-engine/rcv-rst-close-wait/all-rcv-rst-close-wait-tests \
               state-event-engine/rcv-rst-fin-wait-1/all-rcv-rst-fin-wait-1-tests \
               state-event-engine/rcv-rst-closing/all-rcv-rst-closing-tests \
               state-event-engine/rcv-rst-last-ack/all-rcv-rst-last-ack-tests \
               state-event-engine/rcv-rst-fin-wait-2/all-rcv-rst-fin-wait-2-tests \
               state-event-engine/rcv-rst-time-wait/all-rcv-rst-time-wait-tests \
               state-event-engine/rcv-rst-ack-closed/all-rcv-rst-ack-closed-tests \
               state-event-engine/rcv-rst-ack-listen/all-rcv-rst-ack-listen-tests \
               state-event-engine/rcv-rst-ack-syn-sent/all-rcv-rst-ack-syn-sent-tests \
               tcp-over-udp/all-tcp-over-udp-tests

