#!/usr/bin/env tcsh
#
# Copyright (c) 2016 Michael Tuexen
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

set packetdrill = /usr/local/bin/packetdrill
set delay = 1
set limit = 5
set testcases = ( rcv-rst-closed/rcv-rst-closed-secure-ipv4 \
                  rcv-rst-closed/rcv-rst-closed-secure-ipv6 \
                  rcv-rst-listen/rcv-rst-listen-secure-ipv4 \
                  rcv-rst-listen/rcv-rst-listen-secure-ipv6 \
                  rcv-rst-syn-sent/rcv-rst-syn-sent-outside-left-ipv4 \
                  rcv-rst-syn-sent/rcv-rst-syn-sent-outside-left-ipv6 \
                  rcv-rst-syn-sent/rcv-rst-syn-sent-left-edge-ipv4 \
                  rcv-rst-syn-sent/rcv-rst-syn-sent-left-edge-ipv6 \
                  rcv-rst-syn-sent/rcv-rst-syn-sent-outside-right-ipv4 \
                  rcv-rst-syn-sent/rcv-rst-syn-sent-outside-right-ipv6 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-outside-left-secure-ipv4 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-outside-left-secure-ipv6 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-left-edge-secure-ipv4 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-left-edge-secure-ipv6 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-right-edge-secure-ipv4 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-right-edge-secure-ipv6 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-outside-right-secure-ipv4 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-outside-right-secure-ipv6 \
                  rcv-rst-established/rcv-rst-established-outside-left-secure-ipv4 \
                  rcv-rst-established/rcv-rst-established-outside-left-secure-ipv6 \
                  rcv-rst-established/rcv-rst-established-left-edge-secure-ipv4 \
                  rcv-rst-established/rcv-rst-established-left-edge-secure-ipv6 \
                  rcv-rst-established/rcv-rst-established-right-edge-secure-ipv4 \
                  rcv-rst-established/rcv-rst-established-right-edge-secure-ipv6 \
                  rcv-rst-established/rcv-rst-established-outside-right-secure-ipv4 \
                  rcv-rst-established/rcv-rst-established-outside-right-secure-ipv6 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-left-secure-ipv4 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-left-secure-ipv6 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-left-edge-secure-ipv4 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-left-edge-secure-ipv6 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-right-edge-secure-ipv4 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-right-edge-secure-ipv6 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-right-secure-ipv4 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-right-secure-ipv6 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-left-secure-ipv4 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-left-secure-ipv6 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-left-edge-secure-ipv4 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-left-edge-secure-ipv6 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-right-edge-secure-ipv4 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-right-edge-secure-ipv6 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-right-secure-ipv4 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-right-secure-ipv6 \
                  rcv-rst-close-wait/rcv-rst-close-wait-outside-left-secure-ipv4 \
                  rcv-rst-close-wait/rcv-rst-close-wait-outside-left-secure-ipv6 \
                  rcv-rst-close-wait/rcv-rst-close-wait-left-edge-secure-ipv4 \
                  rcv-rst-close-wait/rcv-rst-close-wait-left-edge-secure-ipv6 \
                  rcv-rst-close-wait/rcv-rst-close-wait-right-edge-secure-ipv4 \
                  rcv-rst-close-wait/rcv-rst-close-wait-right-edge-secure-ipv6 \
                  rcv-rst-close-wait/rcv-rst-close-wait-outside-right-secure-ipv4 \
                  rcv-rst-close-wait/rcv-rst-close-wait-outside-right-secure-ipv6 \
                  rcv-rst-closing/rcv-rst-closing-outside-left-secure-ipv4 \
                  rcv-rst-closing/rcv-rst-closing-outside-left-secure-ipv6 \
                  rcv-rst-closing/rcv-rst-closing-left-edge-secure-ipv4 \
                  rcv-rst-closing/rcv-rst-closing-left-edge-secure-ipv6 \
                  rcv-rst-closing/rcv-rst-closing-right-edge-secure-ipv4 \
                  rcv-rst-closing/rcv-rst-closing-right-edge-secure-ipv6 \
                  rcv-rst-closing/rcv-rst-closing-outside-right-secure-ipv4 \
                  rcv-rst-closing/rcv-rst-closing-outside-right-secure-ipv6 \
                  rcv-rst-time-wait/rcv-rst-time-wait-outside-left-secure-ipv4 \
                  rcv-rst-time-wait/rcv-rst-time-wait-outside-left-secure-ipv6 \
                  rcv-rst-time-wait/rcv-rst-time-wait-left-edge-secure-ipv4 \
                  rcv-rst-time-wait/rcv-rst-time-wait-left-edge-secure-ipv6 \
                  rcv-rst-time-wait/rcv-rst-time-wait-right-edge-secure-ipv4 \
                  rcv-rst-time-wait/rcv-rst-time-wait-right-edge-secure-ipv6 \
                  rcv-rst-time-wait/rcv-rst-time-wait-outside-right-secure-ipv4 \
                  rcv-rst-time-wait/rcv-rst-time-wait-outside-right-secure-ipv6 \
                  rcv-rst-last-ack/rcv-rst-last-ack-outside-left-secure-ipv4 \
                  rcv-rst-last-ack/rcv-rst-last-ack-outside-left-secure-ipv6 \
                  rcv-rst-last-ack/rcv-rst-last-ack-left-edge-secure-ipv4 \
                  rcv-rst-last-ack/rcv-rst-last-ack-left-edge-secure-ipv6 \
                  rcv-rst-last-ack/rcv-rst-last-ack-right-edge-secure-ipv4 \
                  rcv-rst-last-ack/rcv-rst-last-ack-right-edge-secure-ipv6 \
                  rcv-rst-last-ack/rcv-rst-last-ack-outside-right-secure-ipv4 \
                  rcv-rst-last-ack/rcv-rst-last-ack-outside-right-secure-ipv6 \
                  rcv-rst-closed/rcv-rst-closed-insecure-ipv4 \
                  rcv-rst-closed/rcv-rst-closed-insecure-ipv6 \
                  rcv-rst-listen/rcv-rst-listen-insecure-ipv4 \
                  rcv-rst-listen/rcv-rst-listen-insecure-ipv6 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-outside-left-insecure-ipv4 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-outside-left-insecure-ipv6 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-left-edge-insecure-ipv4 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-left-edge-insecure-ipv6 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-right-edge-insecure-ipv4 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-right-edge-insecure-ipv6 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-outside-right-insecure-ipv4 \
                  rcv-rst-syn-rcvd/rcv-rst-syn-rcvd-outside-right-insecure-ipv6 \
                  rcv-rst-established/rcv-rst-established-outside-left-insecure-ipv4 \
                  rcv-rst-established/rcv-rst-established-outside-left-insecure-ipv6 \
                  rcv-rst-established/rcv-rst-established-left-edge-insecure-ipv4 \
                  rcv-rst-established/rcv-rst-established-left-edge-insecure-ipv6 \
                  rcv-rst-established/rcv-rst-established-right-edge-insecure-ipv4 \
                  rcv-rst-established/rcv-rst-established-right-edge-insecure-ipv6 \
                  rcv-rst-established/rcv-rst-established-outside-right-insecure-ipv4 \
                  rcv-rst-established/rcv-rst-established-outside-right-insecure-ipv6 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-left-insecure-ipv4 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-left-insecure-ipv6 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-left-edge-insecure-ipv4 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-left-edge-insecure-ipv6 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-right-edge-insecure-ipv4 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-right-edge-insecure-ipv6 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-right-insecure-ipv4 \
                  rcv-rst-fin-wait-1/rcv-rst-fin-wait-1-outside-right-insecure-ipv6 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-left-insecure-ipv4 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-left-insecure-ipv6 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-left-edge-insecure-ipv4 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-left-edge-insecure-ipv6 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-right-edge-insecure-ipv4 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-right-edge-insecure-ipv6 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-right-insecure-ipv4 \
                  rcv-rst-fin-wait-2/rcv-rst-fin-wait-2-outside-right-insecure-ipv6 \
                  rcv-rst-close-wait/rcv-rst-close-wait-outside-left-insecure-ipv4 \
                  rcv-rst-close-wait/rcv-rst-close-wait-outside-left-insecure-ipv6 \
                  rcv-rst-close-wait/rcv-rst-close-wait-left-edge-insecure-ipv4 \
                  rcv-rst-close-wait/rcv-rst-close-wait-left-edge-insecure-ipv6 \
                  rcv-rst-close-wait/rcv-rst-close-wait-right-edge-insecure-ipv4 \
                  rcv-rst-close-wait/rcv-rst-close-wait-right-edge-insecure-ipv6 \
                  rcv-rst-close-wait/rcv-rst-close-wait-outside-right-insecure-ipv4 \
                  rcv-rst-close-wait/rcv-rst-close-wait-outside-right-insecure-ipv6 \
                  rcv-rst-closing/rcv-rst-closing-outside-left-insecure-ipv4 \
                  rcv-rst-closing/rcv-rst-closing-outside-left-insecure-ipv6 \
                  rcv-rst-closing/rcv-rst-closing-left-edge-insecure-ipv4 \
                  rcv-rst-closing/rcv-rst-closing-left-edge-insecure-ipv6 \
                  rcv-rst-closing/rcv-rst-closing-right-edge-insecure-ipv4 \
                  rcv-rst-closing/rcv-rst-closing-right-edge-insecure-ipv6 \
                  rcv-rst-closing/rcv-rst-closing-outside-right-insecure-ipv4 \
                  rcv-rst-closing/rcv-rst-closing-outside-right-insecure-ipv6 \
                  rcv-rst-time-wait/rcv-rst-time-wait-outside-left-insecure-ipv4 \
                  rcv-rst-time-wait/rcv-rst-time-wait-outside-left-insecure-ipv6 \
                  rcv-rst-time-wait/rcv-rst-time-wait-left-edge-insecure-ipv4 \
                  rcv-rst-time-wait/rcv-rst-time-wait-left-edge-insecure-ipv6 \
                  rcv-rst-time-wait/rcv-rst-time-wait-right-edge-insecure-ipv4 \
                  rcv-rst-time-wait/rcv-rst-time-wait-right-edge-insecure-ipv6 \
                  rcv-rst-time-wait/rcv-rst-time-wait-outside-right-insecure-ipv4 \
                  rcv-rst-time-wait/rcv-rst-time-wait-outside-right-insecure-ipv6 \
                  rcv-rst-last-ack/rcv-rst-last-ack-outside-left-insecure-ipv4 \
                  rcv-rst-last-ack/rcv-rst-last-ack-outside-left-insecure-ipv6 \
                  rcv-rst-last-ack/rcv-rst-last-ack-left-edge-insecure-ipv4 \
                  rcv-rst-last-ack/rcv-rst-last-ack-left-edge-insecure-ipv6 \
                  rcv-rst-last-ack/rcv-rst-last-ack-right-edge-insecure-ipv4 \
                  rcv-rst-last-ack/rcv-rst-last-ack-right-edge-insecure-ipv6 \
                  rcv-rst-last-ack/rcv-rst-last-ack-outside-right-insecure-ipv4 \
                  rcv-rst-last-ack/rcv-rst-last-ack-outside-right-insecure-ipv6 )

set rootdir = `/usr/bin/dirname $0`
set passed = 0
set failed = 0
set run = 0
set skipped = 0
set timedout = 0
set first = 1

printf "Name                                                                    Verdict\n"
printf "===============================================================================\n"
foreach testcase ($testcases)
  printf "%-68.68s " `/usr/bin/basename $testcase`
  if ($first == 0) then
    if ($delay != 0) then
      printf "\033[33m%10s\033[0m" "WAITING"
      sleep $delay
      printf "\b\b\b\b\b\b\b\b\b\b"
    endif
  else
    set first = 0
  endif
  printf "\033[33m%10s\033[0m" "RUNNING"
  if (-f ${rootdir}/${testcase}.pkt) then
    timeout $limit $packetdrill ${rootdir}/${testcase}.pkt >& /dev/null
    set result = $status
    set found = 1
  else
    set found = 0
  endif
  printf "\b\b\b\b\b\b\b\b\b\b"
  if ($found == 1) then
    if ($result == 0) then
      @ passed++
      printf "\033[32m%10s\033[0m\n" "PASSED"
    else if ($result == 1) then
      @ failed++
      printf "\033[31m%10s\033[0m\n" "FAILED"
    else
      @ timedout++
      printf "\033[35m%10s\033[0m\n" "TIMEDOUT"
    endif
    @ run++
  else
    printf "\033[34m%10s\033[0m\n" "SKIPPED"
    @ skipped++
  endif
end
printf "===============================================================================\n"
printf "Summary: Number of tests run:       %3u\n" $run
printf "         Number of tests passed:    %3u\n" $passed
printf "         Number of tests failed:    %3u\n" $failed
printf "         Number of tests timed out: %3u\n" $timedout
printf "         Number of tests skipped:   %3u\n" $skipped
